### ISSUE TITLE
TypeError: 'NoneType' object is not callable in NodeJSEngine.__del__()

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-utils#137]
https://github.com/common-workflow-language/cwltool/runs/7649655102?check_suite_focus=true#step:8:54

```
Exception ignored in: <bound method NodeJSEngine.__del__ of <cwl_utils.sandboxjs.NodeJSEngine object at 0x7f35bacd44a8>>
  Traceback (most recent call last):
    File "/home/runner/work/cwltool/cwltool/.tox/py36-unit/lib/python3.6/site-packages/cwl_utils/sandboxjs.py", line 105, in __del__
  TypeError: 'NoneType' object is not callable
  Exception ignored in: <bound method NodeJSEngine.__del__ of <cwl_utils.sandboxjs.NodeJSEngine object at 0x7fcf4edc3668>>
  Traceback (most recent call last):
    File "/home/runner/work/cwltool/cwltool/.tox/py36-unit/lib/python3.6/site-packages/cwl_utils/sandboxjs.py", line 105, in __del__
  TypeError: 'NoneType' object is not callable
```

**Comment by fmigneault** [comment]
I'm seeing this error as well in more recent versions:

https://github.com/crim-ca/weaver/actions/runs/24352439468/job/71129017050?pr=907
```python
Exception ignored in: <function NodeJSEngine.__del__ at 0x7f9e818e63e0>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.13/x64/lib/python3.12/site-packages/cwl_utils/sandboxjs.py", line 111, in __del__
```

**Comment by fmigneault** [comment]
@mr-c Thanks for the fix in https://github.com/common-workflow-language/cwl-utils/commit/0744c4c3ff952ddbfb8397edb11c255415119b9c

Can a new version be released to pin it with cwltool, etc.?
The packages still employ the older https://github.com/common-workflow-language/cwl-utils/releases/tag/v0.41

**Comment by mr-c** [comment]
@fmigneault thank you for the reminder! https://github.com/common-workflow-language/cwl-utils/releases/tag/v0.42 https://pypi.org/project/cwl-utils/0.42/
