### ISSUE TITLE
Create conda package

### ISSUE THREAD

**Issue by kinow** [common-workflow-language/cwl-utils#138]
Quick task after lunch, thought I wouldn't have any issues but I think I found a blocker issue, so documenting what I've done so far. Followed the docs in <https://conda-forge.org/docs/maintainer/adding_pkgs.html>, using `greyskull` (thanks for letting me know about it @mr-c , so convenient!):

```
conda create --name cwl-utils
conda activate cwl-utils
conda install -c conda-forge grayskull
grayskull pypi --strict-conda-forge cwl-utils
mv cwl-utils/ cwl-utils-feedstock
```

Then before creating the pull request to `conda-staged`, I decided to first try to build it locally:

```
conda install conda-build
...staged-recipes/recipes/cwl-utils$ conda build .
```

Where it failed due to the missing `cwl-upgrader`, that's not in Conda Forge yet. Will prepare a recipe for `cwl-upgrader` first, then revisit this PR later.

```
$ conda build .
/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for cwl-utils
INFO:conda_build.metadata:Attempting to finalize metadata for cwl-utils
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /t/ki-e13f1601-f16f-46de-9045-261174f0b13f/conda-forge/linux-64/repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /t/ki-e13f1601-f16f-46de-9045-261174f0b13f/conda-forge/noarch/repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/linux-64/repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/linux-64/repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/channeldata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/channeldata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /t/ki-e13f1601-f16f-46de-9045-261174f0b13f/conda-forge/linux-64 HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/linux-64/ HTTP/1.1" 200 None
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /t/ki-e13f1601-f16f-46de-9045-261174f0b13f/conda-forge/linux-64/python-3.9.13-h2660328_0_cpython.tar.bz2 HTTP/1.1" 200 27981348
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['cwl-utils-0.14-py39_0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/kinow/Development/python/miniconda3/conda-bld/cwl-utils_1659923624853/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl


The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-conda_forge           conda-forge
    _openmp_mutex:    4.5-2_gnu                 conda-forge
    bzip2:            1.0.8-h7f98852_4          conda-forge
    ca-certificates:  2022.6.15-ha878542_0      conda-forge
    ld_impl_linux-64: 2.36.1-hea4e1c9_2         conda-forge
    libffi:           3.4.2-h7f98852_5          conda-forge
    libgcc-ng:        12.1.0-h8d9b700_16        conda-forge
    libgomp:          12.1.0-h8d9b700_16        conda-forge
    libnsl:           2.0.0-h7f98852_0          conda-forge
    libuuid:          2.32.1-h7f98852_1000      conda-forge
    libzlib:          1.2.12-h166bdaf_2         conda-forge
    ncurses:          6.3-h27087fc_1            conda-forge
    openssl:          3.0.5-h166bdaf_1          conda-forge
    pip:              22.2.2-pyhd8ed1ab_0       conda-forge
    python:           3.9.13-h2660328_0_cpython conda-forge
    python_abi:       3.9-2_cp39                conda-forge
    readline:         8.1.2-h0f457ee_0          conda-forge
    setuptools:       63.4.2-py39hf3d152e_0     conda-forge
    sqlite:           3.39.2-h4ff8645_0         conda-forge
    tk:               8.6.12-h27826a3_0         conda-forge
    tzdata:           2022a-h191b570_0          conda-forge
    wheel:            0.37.1-pyhd8ed1ab_0       conda-forge
    xz:               5.2.5-h516909a_1          conda-forge
    zlib:             1.2.12-h166bdaf_2         conda-forge

DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /t/ki-e13f1601-f16f-46de-9045-261174f0b13f/conda-forge/linux-64/openssl-3.0.5-h166bdaf_1.tar.bz2 HTTP/1.1" 200 2958108
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /t/ki-e13f1601-f16f-46de-9045-261174f0b13f/conda-forge/linux-64/setuptools-63.4.2-py39hf3d152e_0.tar.bz2 HTTP/1.1" 200 1406014
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

Leaving build/test directories:
  Work:
 /home/kinow/Development/python/miniconda3/conda-bld/work 
  Test:
 /home/kinow/Development/python/miniconda3/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/kinow/Development/python/miniconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p 
  Build:
source activate  /home/kinow/Development/python/miniconda3/conda-bld/_build_env 


Traceback (most recent call last):
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda_build/environ.py", line 799, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda/common/io.py", line 86, in decorated
    return f(*args, **kwds)
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda/plan.py", line 473, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 195, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 313, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 603, in _add_specs
    explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda/resolve.py", line 555, in _get_package_pool
    pool = self.get_reduced_index(specs)
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda/common/io.py", line 86, in decorated
    return f(*args, **kwds)
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda/resolve.py", line 576, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda/resolve.py", line 288, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - cwl-upgrader[version='>=1.2']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinow/Development/python/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 488, in main
    execute(sys.argv[1:])
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 477, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda_build/build.py", line 3088, in build_tree
    packages_from_this = build(metadata, stats,
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda_build/build.py", line 2128, in build
    create_build_envs(top_level_pkg, notest)
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda_build/build.py", line 2006, in create_build_envs
    raise e
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda_build/build.py", line 1985, in create_build_envs
    environ.get_install_actions(m.config.test_prefix,
  File "/home/kinow/Development/python/miniconda3/lib/python3.9/site-packages/conda_build/environ.py", line 801, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"cwl-upgrader[version='>=1.2']"}
```

-Bruno

**Comment by kinow** [comment]
Huh, tried again and now it worked. The `cwltool` package has a dependency on `cwl-utils` that's not published, so I think conda is handling the missing conda packages via pip (I thought it wouldn't resolve pip packages automatically). Let me try preparing a PR for `cwl-utils` to conda-forge.

**Comment by kinow** [comment]
@mr-c I think this can be closed now?
