### ISSUE TITLE
AttributeError: 'CommentedMap' object has no attribute 'decode'

### ISSUE THREAD

**Issue by giannisdoukas** [common-workflow-language/cwl-utils#16]
I think there is an issue regarding load_document function. I am trying to parse to the following workflow and take the error bellow. For the same workflow, the cwltool --validate says that the workflow is valid. 

```
top = parser_v1_0.load_document('/Users/dks/Desktop/play/all.cwl')
Traceback (most recent call last):
  File "/Users/dks/Workspaces/CWLKernel/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-237afbeeffc9>", line 1, in <module>
    top = parser_v1_0.load_document('/Users/dks/Desktop/play/all.cwl')
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 10395, in load_document
    return _document_load(union_of_CommandLineToolLoader_or_ExpressionToolLoader_or_WorkflowLoader_or_array_of_union_of_CommandLineToolLoader_or_ExpressionToolLoader_or_WorkflowLoader, doc, baseuri, loadingOptions)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 471, in _document_load
    loader, loadingOptions.fetcher.urljoin(baseuri, doc), loadingOptions
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 513, in _document_load_by_url
    return _document_load(loader, result, url, loadingOptions)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 485, in _document_load
    return loader.load(doc["$graph"], baseuri, loadingOptions)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 324, in load
    return t.load(doc, baseuri, loadingOptions, docRoot=docRoot)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 270, in load
    doc[i], _UnionLoader((self, self.items)), baseuri, loadingOptions
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 125, in load_field
    return fieldtype.load(val, baseuri, loadingOptions)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 324, in load
    return t.load(doc, baseuri, loadingOptions, docRoot=docRoot)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 324, in load
    return t.load(doc, baseuri, loadingOptions, docRoot=docRoot)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 308, in load
    return self.classtype.fromDoc(doc, baseuri, loadingOptions, docRoot=docRoot)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 9547, in fromDoc
    'steps'), idmap_steps_union_of_array_of_WorkflowStepLoader, baseuri, loadingOptions)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 125, in load_field
    return fieldtype.load(val, baseuri, loadingOptions)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 464, in load
    return self.inner.load(doc, baseuri, loadingOptions)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 324, in load
    return t.load(doc, baseuri, loadingOptions, docRoot=docRoot)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 270, in load
    doc[i], _UnionLoader((self, self.items)), baseuri, loadingOptions
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 125, in load_field
    return fieldtype.load(val, baseuri, loadingOptions)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 324, in load
    return t.load(doc, baseuri, loadingOptions, docRoot=docRoot)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 308, in load
    return self.classtype.fromDoc(doc, baseuri, loadingOptions, docRoot=docRoot)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 9107, in fromDoc
    'out'), uri_union_of_array_of_union_of_strtype_or_WorkflowStepOutputLoader_True_False_None, baseuri, loadingOptions)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 125, in load_field
    return fieldtype.load(val, baseuri, loadingOptions)
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 357, in load
    for i in doc
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 357, in <listcomp>
    for i in doc
  File "/Users/dks/Workspaces/cwl-utils/cwl_utils/parser_v1_0.py", line 175, in expand_url
    split = urlsplit(url)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 418, in urlsplit
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 123, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 107, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 107, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 'CommentedMap' object has no attribute 'decode'
```

```
cwltool --validate /Users/dks/Desktop/play/all.cwl
INFO /opt/cwltool/bin/cwltool 3.0.20200324120055
INFO Resolved '/Users/dks/Desktop/play/all.cwl' to 'file:///Users/dks/Desktop/play/all.cwl'
/Users/dks/Desktop/play/all.cwl is valid CWL.
```

```cwl
{
    "$graph": [
        {
            "class": "CommandLineTool",
            "id": "#head.cwl",
            "baseCommand": [
                "head"
            ],
            "inputs": [
                {
                    "id": "#head.cwl/number_of_lines",
                    "type": [
                        "null",
                        "int"
                    ],
                    "inputBinding": {
                        "position": 0,
                        "prefix": "-n"
                    }
                },
                {
                    "id": "#head.cwl/inputfile",
                    "type": [
                        "null",
                        "File"
                    ],
                    "inputBinding": {
                        "position": 1
                    }
                }
            ],
            "outputs": [
                {
                    "id": "#head.cwl/headoutput",
                    "type": "stdout"
                }
            ],
            "label": "head",
            "stdout": "head.out",
            "$namespaces": {
                "sbg": "https://www.sevenbridges.com/"
            }
        },
        {
            "class": "CommandLineTool",
            "id": "#tail.cwl",
            "baseCommand": [
                "tail"
            ],
            "inputs": [
                {
                    "id": "#tail.cwl/tailnumber_of_lines",
                    "type": [
                        "null",
                        "int"
                    ],
                    "inputBinding": {
                        "position": 0,
                        "prefix": "-n"
                    }
                },
                {
                    "id": "#tail.cwl/tailinputfile",
                    "type": "File",
                    "inputBinding": {
                        "position": 1
                    }
                }
            ],
            "outputs": [
                {
                    "id": "#tail.cwl/output",
                    "type": "stdout"
                }
            ],
            "label": "tail"
        },
        {
            "class": "Workflow",
            "id": "#main",
            "label": "w",
            "inputs": [
                {
                    "id": "#maininput",
                    "type": "File",
                    "https://www.sevenbridges.com/x": -427,
                    "https://www.sevenbridges.com/y": -78
                }
            ],
            "outputs": [
                {
                    "id": "#output",
                    "outputSource": [
                        "#tail/output"
                    ],
                    "type": [
                        "null",
                        "File"
                    ],
                    "https://www.sevenbridges.com/x": 151,
                    "https://www.sevenbridges.com/y": -71
                }
            ],
            "steps": [
                {
                    "id": "#head",
                    "in": [
                        {
                            "id": "#head/number_of_lines",
                            "default": 5
                        },
                        {
                            "id": "#head/inputfile",
                            "source": "#maininput"
                        }
                    ],
                    "out": [
                        {
                            "id": "#head/headoutput"
                        }
                    ],
                    "run": "#head.cwl",
                    "label": "head",
                    "https://www.sevenbridges.com/x": -267,
                    "https://www.sevenbridges.com/y": -80
                },
                {
                    "id": "#tail",
                    "in": [
                        {
                            "id": "#tail/tailnumber_of_lines",
                            "default": 5
                        },
                        {
                            "id": "#tail/tailinputfile",
                            "source": "#head/headoutput"
                        }
                    ],
                    "out": [
                        {
                            "id": "#tail/output"
                        }
                    ],
                    "run": "#tail.cwl",
                    "label": "tail",
                    "https://www.sevenbridges.com/x": -84,
                    "https://www.sevenbridges.com/y": -77
                }
            ],
            "requirements": [
                {
                    "class": "MultipleInputFeatureRequirement"
                }
            ]
        }
    ],
    "cwlVersion": "v1.0"
}
```

```cwl
{
    "$graph": [
        {
            "class": "CommandLineTool",
            "id": "#awk.cwl",
            "baseCommand": [
                "awk"
            ],
            "inputs": [
                {
                    "id": "#awk.cwl/delim",
                    "type": [
                        "null",
                        "string"
                    ],
                    "inputBinding": {
                        "position": 0,
                        "prefix": "-F",
                        "valueFrom": "$(inputs.delim)"
                    }
                },
                {
                    "id": "#awk.cwl/column",
                    "type": [
                        "null",
                        "int"
                    ],
                    "inputBinding": {
                        "position": 1,
                        "valueFrom": "$(\"{print $\" + inputs.column + \"}\")"
                    }
                },
                {
                    "id": "#awk.cwl/input",
                    "type": [
                        "null",
                        "File"
                    ],
                    "inputBinding": {
                        "position": 4
                    }
                }
            ],
            "outputs": [
                {
                    "id": "#awk.cwl/output",
                    "type": "stdout"
                }
            ],
            "label": "awk",
            "requirements": [
                {
                    "class": "InlineJavascriptRequirement"
                }
            ],
            "stdout": "out.txt",
            "$namespaces": {
                "sbg": "https://www.sevenbridges.com/"
            }
        },
        {
            "class": "CommandLineTool",
            "id": "#head.cwl",
            "baseCommand": [
                "head"
            ],
            "inputs": [
                {
                    "id": "#head.cwl/number_of_lines",
                    "type": [
                        "null",
                        "int"
                    ],
                    "inputBinding": {
                        "position": 0,
                        "prefix": "-n"
                    }
                },
                {
                    "id": "#head.cwl/inputfile",
                    "type": "stdin"
                }
            ],
            "outputs": [
                {
                    "id": "#head.cwl/output",
                    "type": "stdout"
                }
            ],
            "label": "head"
        },
        {
            "class": "Workflow",
            "id": "#main",
            "label": "w",
            "inputs": [
                {
                    "id": "#maininput",
                    "type": [
                        "null",
                        "File"
                    ],
                    "https://www.sevenbridges.com/x": -458.25,
                    "https://www.sevenbridges.com/y": -9
                }
            ],
            "outputs": [
                {
                    "id": "#output",
                    "outputSource": [
                        "#head/output"
                    ],
                    "type": [
                        "null",
                        "File"
                    ],
                    "https://www.sevenbridges.com/x": -45.25,
                    "https://www.sevenbridges.com/y": -8
                }
            ],
            "steps": [
                {
                    "id": "#awk",
                    "in": [
                        {
                            "id": "#awk/delim",
                            "default": ","
                        },
                        {
                            "id": "#awk/column",
                            "default": 1
                        },
                        {
                            "id": "#awk/input",
                            "source": "#maininput"
                        }
                    ],
                    "out": [
                        {
                            "id": "#awk/output"
                        }
                    ],
                    "run": "#awk.cwl",
                    "label": "awk",
                    "https://www.sevenbridges.com/x": -332,
                    "https://www.sevenbridges.com/y": -8
                },
                {
                    "id": "#head",
                    "in": [
                        {
                            "id": "#head/number_of_lines",
                            "default": 5
                        },
                        {
                            "id": "#head/inputfile",
                            "source": "#awk/output"
                        }
                    ],
                    "out": [
                        {
                            "id": "#head/output"
                        }
                    ],
                    "run": "#head.cwl",
                    "label": "head",
                    "https://www.sevenbridges.com/x": -187,
                    "https://www.sevenbridges.com/y": -9
                }
            ],
            "requirements": []
        }
    ],
    "cwlVersion": "v1.0"
}
```

**Comment by illusional** [comment]
Hey @giannisdoukas and @mr-c, seeing this problem as well. It seems to be related to a WorkflowStep output, eg:

DOESN'T WORK:

```cwl
steps:
- id: hello
  label: Echo
  in:
  - id: inp
    source: inp
  run: tools/echo_v1_0_0.cwl
  out:
  - id: out
```

WORKS:

```cwl
steps:
- id: hello
  label: Echo
  in:
  - id: inp
    source: inp
  run: tools/echo_v1_0_0.cwl
  out: ["out"]
```

Still investigating this more, but just interesting to note.

**Comment by mr-c** [comment]
I suspect this is related to https://github.com/common-workflow-language/schema_salad/issues/359#issuecomment-725393788 (`_URILoader` doesn't consider the union type it was given as it immediately tries to parse every component as a URI)

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-language/cwl-utils/pull/51
