### ISSUE TITLE
load_document fails with $schemas field?

### ISSUE THREAD

**Issue by leipzig** [common-workflow-language/cwl-utils#25]
Hello,
Thanks for developing cwl-utils. I am having trouble using the parser. It appears to work with tools that don't have `$schemas`, but fails otherwise
```
>>> import cwl_utils.parser_v1_0 as parser
>>> parser.load_document("https://raw.githubusercontent.com/common-workflow-library/bio-cwl-tools/release/bedtools/bedtools_bamtobed_2.cwl")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/leipzig/Documents/dev/cwl-utils/lib/python3.6/site-packages/cwl_utils/parser_v1_0.py", line 10395, in load_document
    return _document_load(union_of_CommandLineToolLoader_or_ExpressionToolLoader_or_WorkflowLoader_or_array_of_union_of_CommandLineToolLoader_or_ExpressionToolLoader_or_WorkflowLoader, doc, baseuri, loadingOptions)
  File "/Users/leipzig/Documents/dev/cwl-utils/lib/python3.6/site-packages/cwl_utils/parser_v1_0.py", line 471, in _document_load
    loader, loadingOptions.fetcher.urljoin(baseuri, doc), loadingOptions
  File "/Users/leipzig/Documents/dev/cwl-utils/lib/python3.6/site-packages/cwl_utils/parser_v1_0.py", line 513, in _document_load_by_url
    return _document_load(loader, result, url, loadingOptions)
  File "/Users/leipzig/Documents/dev/cwl-utils/lib/python3.6/site-packages/cwl_utils/parser_v1_0.py", line 487, in _document_load
    return loader.load(doc, baseuri, loadingOptions, docRoot=baseuri)
  File "/Users/leipzig/Documents/dev/cwl-utils/lib/python3.6/site-packages/cwl_utils/parser_v1_0.py", line 331, in load
    raise ValidationException("", None, errors, "-")
schema_salad.exceptions.ValidationException: - tried _RecordLoader but
  Trying 'CommandLineTool'
    invalid field `$schemas`, expected one of: `id`, `inputs`, `outputs`, `requirements`, `hints`, `label`, `doc`, `cwlVersion`, `class`, `baseCommand`, `arguments`, `stdin`, `stderr`, `stdout`, `successCodes`, `temporaryFailCodes`, `permanentFailCodes`
- tried _RecordLoader but
  Not a ExpressionTool
- tried _RecordLoader but
  Not a Workflow
- tried _ArrayLoader but
  Expected a list
```

my environment
```
(cwl-utils) (base) Leipzig:cwl-utils leipzig$ pip freeze
CacheControl==0.11.7
certifi==2020.4.5.2
chardet==3.0.4
cwl-utils==0.5
idna==2.9
isodate==0.6.0
lockfile==0.12.2
mistune==0.8.4
pyparsing==2.4.7
rdflib==4.2.2
rdflib-jsonld==0.5.0
requests==2.24.0
ruamel.yaml==0.16.5
ruamel.yaml.clib==0.2.0
schema-salad==6.0.20200601095207
six==1.15.0
typing-extensions==3.7.4.2
urllib3==1.25.9
```

I imagine I need to pass `skip-schemas` to SchemaSalad somehow like 
`parser.load_document("https://raw.githubusercontent.com/common-workflow-library/bio-cwl-tools/release/bedtools/bedtools_bamtobed_2.cwl",loadingOptions=LoadingOptions(skipschemas=True))`but it is beyond me.

Thanks for your help!

**Comment by leipzig** [comment]
hi @mr-c any thoughts as to what is happening here?

**Comment by mr-c** [comment]
Hey @leipzig , this is a missing feature of schema-salad so I've filled https://github.com/common-workflow-language/schema_salad/issues/345
