### ISSUE TITLE
How to execute docker_extract.py ? I got error

### ISSUE THREAD

**Issue by manabuishii** [common-workflow-language/cwl-utils#7]
I try to use `docker_extract.py` .

Python version: `3.7.3`

But I get the error

change directory to `cwl-utils` ( git clone directory ) and execute.

```console
$ python cwl_utils/docker_extract.py --singularity ../ ../head-container.cwl
Traceback (most recent call last):
  File "cwl_utils/docker_extract.py", line 8, in <module>
    from cwl_utils.image_puller import DockerImagePuller, SingularityImagePuller
ModuleNotFoundError: No module named 'cwl_utils.image_puller'
```

change directory to `cwl-utils/cwl_utils`

```console
$ cd cwl_utils/
$ python docker_extract.py --singularity ../../ ../../head-container.cwl
Traceback (most recent call last):
  File "docker_extract.py", line 6, in <module>
    from cwl_utils.image_puller import DockerImagePuller, SingularityImagePuller
ModuleNotFoundError: No module named 'cwl_utils.image_puller'
```

WORKAROUND:

```python
from cwl_utils.image_puller import DockerImagePuller, SingularityImagePuller
```

to

```python
from image_puller import DockerImagePuller, SingularityImagePuller
```

it works fine.

I want to know how to execute `docker_extract.py` without my WORKAROUND.

**Comment by mr-c** [comment]
Hey @manabuishii ; `cwl-utils` is now pip installable, so that should fix the problem for you.

https://pypi.org/project/cwl-utils/
